### ISSUE TITLE
Align NFT naming

### ISSUE THREAD

**Issue by frol** [telezhnaya/near_enhanced_api#15]
https://github.com/near/near-enhanced-api-server/blob/feab5c73ab0fe58591377131076663af3c888931/src/api_models.rs#L65

There is no "collection" term in [NEP-171](https://nomicon.io/Standards/Tokens/NonFungibleToken/Core). I got totally lost with NftCollectionOverviewResponse, NftCollectionByContractResponse, NonFungibleToken, and their mix between CoinBalancesResponse and NearHistoryResponse.

I suggest come up with some terminology and extract these into separate files.

**Comment by telezhnaya** [comment]
@frol It's much cleaner now, please have a look again

**Comment by frol** [comment]
The new project structure and naming is much easier to reason about!
