### ISSUE TITLE
Update Overview Docs

### ISSUE THREAD

**Issue by TiffanyGYJ** [telezhnaya/near_enhanced_api#34]
Add this in the Page

> Try out our newly released Enhanced APIs - Balances (in Beta) and get what you need for all kinds of balances and token information at ease. 
> 
> Call single Pagoda API endpoint to access both our speedy RPC(instructions in Keys tab, and we support all [NEAR RPC APIs](https://docs.near.org/api/rpc/access-keys)) and Enhanced APIs using the endpoint in the API URL box, no URL switch needed between RPC and Enhanced API usage, varies by Network 
> 
> https://near-testnet.api.pagoda.co
> 
> https://near-mainnet.api.pagoda.co
> 
> Grab your API keys and give it a try! We will be adding more advanced Enhanced APIs in our offering, so stay tuned. Get the data you need without extra processing, NEAR Blockchain data query has never been easier! 
> We would love to hear from you on the data APIs you need, please leave feedback using the widget in the lower-right corner.

This should be how it looks like 
<img width="1624" alt="image-20220831-192528" src="https://user-images.githubusercontent.com/35774078/188175372-89229e51-53b1-4616-8f8c-c655bfbbc9d0.png">

**Comment by frol** [comment]
Closed in #35
