### ISSUE TITLE
dotenv update

### ISSUE THREAD

**Issue by waldmatias** [telezhnaya/near_enhanced_api#42]
Hey guys! I see you are still using dotenv 0.15.x which has been stale for quite some time (around 2020). In the spirit of keeping things up to date, you may want to switch (prior checks made of course) to dotenvy which is an active fork of dotenv. [https://crates.io/crates/dotenvy/0.15.3](https://crates.io/crates/dotenvy/0.15.3).

**Comment by frol** [comment]
@waldmatias Thanks for the heads up! So far we are not facing any problems with `dotenv`, so we will keep it for now and consider completely replacing it with some proper configuration setup in the future.
