### ISSUE TITLE
All the endpoints return 404 if API_BASE_PATH is specified

### ISSUE THREAD

**Issue by telezhnaya** [telezhnaya/near_enhanced_api#50]
If I put to .env this:
```
API_BASE_PATH=/olya
```
I have 404 as the response to all the endpoints on my local machine. 
Magically, it works fine in production (Pavel showed it on Monday)

@roshaans could you please investigate?

**Comment by roshaans** [comment]
We currently we use the base path to generate a request from the Swagger UI but we do not make our endpoints available from the base path.

The reason it works in production is because we reroute the user with some middleware by omitting the base path from the URL.
